# Generated by Django 6.0.3 on 2026-04-08 01:37

from django.db import migrations, models

# This migration creates the UserProfile model, which will be used to store user information such as email and password for authentication purposes when sending emails through the SMTP client.
class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
