# Generated by Django 6.0.3 on 2026-04-08 02:57

from django.db import migrations

# This migration renames the UserProfile model to User to better reflect its purpose and align with common naming conventions for user-related models in Django applications.
class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User',
        ),
    ]
